(ns dpu_smartnic.actor
  "dpu_smartnic clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). DPU / SmartNIC data-path accelerator design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; Dpu
   {:db/ident :dpu_smartnic.Dpu/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dpu_smartnic.Dpu/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Dpu/vendor :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Dpu/portsGbps :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Dpu/cores :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Dpu/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Dpu/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; PacketPipeline
   {:db/ident :dpu_smartnic.PacketPipeline/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dpu_smartnic.PacketPipeline/dpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.PacketPipeline/stages :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.PacketPipeline/throughputMpps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.PacketPipeline/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.PacketPipeline/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; RdmaEngine
   {:db/ident :dpu_smartnic.RdmaEngine/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dpu_smartnic.RdmaEngine/dpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.RdmaEngine/protocol :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.RdmaEngine/queues :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.RdmaEngine/latencyUs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.RdmaEngine/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.RdmaEngine/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ArmComplex
   {:db/ident :dpu_smartnic.ArmComplex/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dpu_smartnic.ArmComplex/dpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.ArmComplex/cores :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.ArmComplex/frequencyGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.ArmComplex/isa :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.ArmComplex/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.ArmComplex/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; FlowTable
   {:db/ident :dpu_smartnic.FlowTable/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dpu_smartnic.FlowTable/dpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.FlowTable/entries :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.FlowTable/matchFields :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.FlowTable/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.FlowTable/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Offload
   {:db/ident :dpu_smartnic.Offload/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :dpu_smartnic.Offload/dpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Offload/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Offload/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Offload/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :dpu_smartnic.Offload/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"Dpu" "PacketPipeline" "RdmaEngine" "ArmComplex" "FlowTable" "Offload"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "dpu_smartnic: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "dpu_smartnic: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "dpu_smartnic: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── Dpu ────────────────────────────────────────────────────────────────
(defn create-dpu
  "Create a Dpu."
  [port data]
  (require-fields data ["name" "vendor"])
  (let [id (new-id "dpu_dpu")
        e {:db/id id
           :dpu_smartnic.Dpu/id id
           :dpu_smartnic.Dpu/name (get data :name)
           :dpu_smartnic.Dpu/vendor (get data :vendor)
           :dpu_smartnic.Dpu/portsGbps (as-long (get data :portsGbps))
           :dpu_smartnic.Dpu/cores (as-long (get data :cores))
           :dpu_smartnic.Dpu/createdAt (now)
           :dpu_smartnic.Dpu/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-dpus
  "List Dpu with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-dpus port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dpu_smartnic.Dpu/id))
         rows (apply-filters rows (:filter opts) [:dpu_smartnic.Dpu/name :dpu_smartnic.Dpu/vendor :dpu_smartnic.Dpu/portsGbps :dpu_smartnic.Dpu/cores])]
     (paginate rows opts))))

(defn get-dpu
  "Retrieve a Dpu by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-dpu port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-dpu
  "Update a Dpu; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :dpu_smartnic.Dpu/name (get data :name)]))
                   (cond-> (contains? data :vendor) (conj [:db/add id :dpu_smartnic.Dpu/vendor (get data :vendor)]))
                   (cond-> (contains? data :portsGbps) (conj [:db/add id :dpu_smartnic.Dpu/portsGbps (as-long (get data :portsGbps))]))
                   (cond-> (contains? data :cores) (conj [:db/add id :dpu_smartnic.Dpu/cores (as-long (get data :cores))]))
                   (conj [:db/add id :dpu_smartnic.Dpu/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-dpu
  "Delete a Dpu."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── PacketPipeline ────────────────────────────────────────────────────────────────
(defn create-packet-pipeline
  "Create a PacketPipeline."
  [port data]
  (require-fields data ["stages" "throughputMpps"])
  (let [id (new-id "dpu_pac")
        e {:db/id id
           :dpu_smartnic.PacketPipeline/id id
           :dpu_smartnic.PacketPipeline/dpuId (get data :dpuId)
           :dpu_smartnic.PacketPipeline/stages (as-long (get data :stages))
           :dpu_smartnic.PacketPipeline/throughputMpps (as-double (get data :throughputMpps))
           :dpu_smartnic.PacketPipeline/createdAt (now)
           :dpu_smartnic.PacketPipeline/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-packet-pipelines
  "List PacketPipeline with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-packet-pipelines port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dpu_smartnic.PacketPipeline/id))
         rows (apply-filters rows (:filter opts) [:dpu_smartnic.PacketPipeline/dpuId :dpu_smartnic.PacketPipeline/stages :dpu_smartnic.PacketPipeline/throughputMpps])]
     (paginate rows opts))))

(defn get-packet-pipeline
  "Retrieve a PacketPipeline by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-packet-pipeline port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :dpuId) (get rec :dpu_smartnic.PacketPipeline/dpuId))
         (assoc :dpuId-obj (-pull port (get rec :dpu_smartnic.PacketPipeline/dpuId))))))))

(defn update-packet-pipeline
  "Update a PacketPipeline; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dpuId) (conj [:db/add id :dpu_smartnic.PacketPipeline/dpuId (get data :dpuId)]))
                   (cond-> (contains? data :stages) (conj [:db/add id :dpu_smartnic.PacketPipeline/stages (as-long (get data :stages))]))
                   (cond-> (contains? data :throughputMpps) (conj [:db/add id :dpu_smartnic.PacketPipeline/throughputMpps (as-double (get data :throughputMpps))]))
                   (conj [:db/add id :dpu_smartnic.PacketPipeline/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-packet-pipeline
  "Delete a PacketPipeline."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── RdmaEngine ────────────────────────────────────────────────────────────────
(defn create-rdma-engine
  "Create a RdmaEngine."
  [port data]
  (require-fields data ["protocol" "queues"])
  (let [id (new-id "dpu_rdm")
        e {:db/id id
           :dpu_smartnic.RdmaEngine/id id
           :dpu_smartnic.RdmaEngine/dpuId (get data :dpuId)
           :dpu_smartnic.RdmaEngine/protocol (get data :protocol)
           :dpu_smartnic.RdmaEngine/queues (as-long (get data :queues))
           :dpu_smartnic.RdmaEngine/latencyUs (as-double (get data :latencyUs))
           :dpu_smartnic.RdmaEngine/createdAt (now)
           :dpu_smartnic.RdmaEngine/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-rdma-engines
  "List RdmaEngine with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-rdma-engines port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dpu_smartnic.RdmaEngine/id))
         rows (apply-filters rows (:filter opts) [:dpu_smartnic.RdmaEngine/dpuId :dpu_smartnic.RdmaEngine/protocol :dpu_smartnic.RdmaEngine/queues :dpu_smartnic.RdmaEngine/latencyUs])]
     (paginate rows opts))))

(defn get-rdma-engine
  "Retrieve a RdmaEngine by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-rdma-engine port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :dpuId) (get rec :dpu_smartnic.RdmaEngine/dpuId))
         (assoc :dpuId-obj (-pull port (get rec :dpu_smartnic.RdmaEngine/dpuId))))))))

(defn update-rdma-engine
  "Update a RdmaEngine; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dpuId) (conj [:db/add id :dpu_smartnic.RdmaEngine/dpuId (get data :dpuId)]))
                   (cond-> (contains? data :protocol) (conj [:db/add id :dpu_smartnic.RdmaEngine/protocol (get data :protocol)]))
                   (cond-> (contains? data :queues) (conj [:db/add id :dpu_smartnic.RdmaEngine/queues (as-long (get data :queues))]))
                   (cond-> (contains? data :latencyUs) (conj [:db/add id :dpu_smartnic.RdmaEngine/latencyUs (as-double (get data :latencyUs))]))
                   (conj [:db/add id :dpu_smartnic.RdmaEngine/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-rdma-engine
  "Delete a RdmaEngine."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ArmComplex ────────────────────────────────────────────────────────────────
(defn create-arm-complex
  "Create a ArmComplex."
  [port data]
  (require-fields data ["cores" "frequencyGhz"])
  (let [id (new-id "dpu_arm")
        e {:db/id id
           :dpu_smartnic.ArmComplex/id id
           :dpu_smartnic.ArmComplex/dpuId (get data :dpuId)
           :dpu_smartnic.ArmComplex/cores (as-long (get data :cores))
           :dpu_smartnic.ArmComplex/frequencyGhz (as-double (get data :frequencyGhz))
           :dpu_smartnic.ArmComplex/isa (get data :isa)
           :dpu_smartnic.ArmComplex/createdAt (now)
           :dpu_smartnic.ArmComplex/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-arm-complexes
  "List ArmComplex with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-arm-complexes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dpu_smartnic.ArmComplex/id))
         rows (apply-filters rows (:filter opts) [:dpu_smartnic.ArmComplex/dpuId :dpu_smartnic.ArmComplex/cores :dpu_smartnic.ArmComplex/frequencyGhz :dpu_smartnic.ArmComplex/isa])]
     (paginate rows opts))))

(defn get-arm-complex
  "Retrieve a ArmComplex by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-arm-complex port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :dpuId) (get rec :dpu_smartnic.ArmComplex/dpuId))
         (assoc :dpuId-obj (-pull port (get rec :dpu_smartnic.ArmComplex/dpuId))))))))

(defn update-arm-complex
  "Update a ArmComplex; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dpuId) (conj [:db/add id :dpu_smartnic.ArmComplex/dpuId (get data :dpuId)]))
                   (cond-> (contains? data :cores) (conj [:db/add id :dpu_smartnic.ArmComplex/cores (as-long (get data :cores))]))
                   (cond-> (contains? data :frequencyGhz) (conj [:db/add id :dpu_smartnic.ArmComplex/frequencyGhz (as-double (get data :frequencyGhz))]))
                   (cond-> (contains? data :isa) (conj [:db/add id :dpu_smartnic.ArmComplex/isa (get data :isa)]))
                   (conj [:db/add id :dpu_smartnic.ArmComplex/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-arm-complex
  "Delete a ArmComplex."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── FlowTable ────────────────────────────────────────────────────────────────
(defn create-flow-table
  "Create a FlowTable."
  [port data]
  (require-fields data ["entries" "matchFields"])
  (let [id (new-id "dpu_flo")
        e {:db/id id
           :dpu_smartnic.FlowTable/id id
           :dpu_smartnic.FlowTable/dpuId (get data :dpuId)
           :dpu_smartnic.FlowTable/entries (as-long (get data :entries))
           :dpu_smartnic.FlowTable/matchFields (as-long (get data :matchFields))
           :dpu_smartnic.FlowTable/createdAt (now)
           :dpu_smartnic.FlowTable/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-flow-tables
  "List FlowTable with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-flow-tables port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dpu_smartnic.FlowTable/id))
         rows (apply-filters rows (:filter opts) [:dpu_smartnic.FlowTable/dpuId :dpu_smartnic.FlowTable/entries :dpu_smartnic.FlowTable/matchFields])]
     (paginate rows opts))))

(defn get-flow-table
  "Retrieve a FlowTable by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-flow-table port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :dpuId) (get rec :dpu_smartnic.FlowTable/dpuId))
         (assoc :dpuId-obj (-pull port (get rec :dpu_smartnic.FlowTable/dpuId))))))))

(defn update-flow-table
  "Update a FlowTable; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dpuId) (conj [:db/add id :dpu_smartnic.FlowTable/dpuId (get data :dpuId)]))
                   (cond-> (contains? data :entries) (conj [:db/add id :dpu_smartnic.FlowTable/entries (as-long (get data :entries))]))
                   (cond-> (contains? data :matchFields) (conj [:db/add id :dpu_smartnic.FlowTable/matchFields (as-long (get data :matchFields))]))
                   (conj [:db/add id :dpu_smartnic.FlowTable/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-flow-table
  "Delete a FlowTable."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Offload ────────────────────────────────────────────────────────────────
(defn create-offload
  "Create a Offload."
  [port data]
  (require-fields data ["kind" "status"])
  (let [id (new-id "dpu_off")
        e {:db/id id
           :dpu_smartnic.Offload/id id
           :dpu_smartnic.Offload/dpuId (get data :dpuId)
           :dpu_smartnic.Offload/kind (get data :kind)
           :dpu_smartnic.Offload/status (get data :status)
           :dpu_smartnic.Offload/createdAt (now)
           :dpu_smartnic.Offload/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-offloads
  "List Offload with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-offloads port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :dpu_smartnic.Offload/id))
         rows (apply-filters rows (:filter opts) [:dpu_smartnic.Offload/dpuId :dpu_smartnic.Offload/kind :dpu_smartnic.Offload/status])]
     (paginate rows opts))))

(defn get-offload
  "Retrieve a Offload by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-offload port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :dpuId) (get rec :dpu_smartnic.Offload/dpuId))
         (assoc :dpuId-obj (-pull port (get rec :dpu_smartnic.Offload/dpuId))))))))

(defn update-offload
  "Update a Offload; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dpuId) (conj [:db/add id :dpu_smartnic.Offload/dpuId (get data :dpuId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :dpu_smartnic.Offload/kind (get data :kind)]))
                   (cond-> (contains? data :status) (conj [:db/add id :dpu_smartnic.Offload/status (get data :status)]))
                   (conj [:db/add id :dpu_smartnic.Offload/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-offload
  "Delete a Offload."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/dpus" :op :create :entity "Dpu"}
   {:method "GET" :path "/v1/dpus" :op :list :entity "Dpu"}
   {:method "GET" :path "/v1/dpus/:id" :op :get :entity "Dpu"}
   {:method "PATCH" :path "/v1/dpus/:id" :op :update :entity "Dpu"}
   {:method "DELETE" :path "/v1/dpus/:id" :op :delete :entity "Dpu"}
   {:method "POST" :path "/v1/packetpipelines" :op :create :entity "PacketPipeline"}
   {:method "GET" :path "/v1/packetpipelines" :op :list :entity "PacketPipeline"}
   {:method "GET" :path "/v1/packetpipelines/:id" :op :get :entity "PacketPipeline"}
   {:method "PATCH" :path "/v1/packetpipelines/:id" :op :update :entity "PacketPipeline"}
   {:method "DELETE" :path "/v1/packetpipelines/:id" :op :delete :entity "PacketPipeline"}
   {:method "POST" :path "/v1/rdmaengines" :op :create :entity "RdmaEngine"}
   {:method "GET" :path "/v1/rdmaengines" :op :list :entity "RdmaEngine"}
   {:method "GET" :path "/v1/rdmaengines/:id" :op :get :entity "RdmaEngine"}
   {:method "PATCH" :path "/v1/rdmaengines/:id" :op :update :entity "RdmaEngine"}
   {:method "DELETE" :path "/v1/rdmaengines/:id" :op :delete :entity "RdmaEngine"}
   {:method "POST" :path "/v1/armcomplexes" :op :create :entity "ArmComplex"}
   {:method "GET" :path "/v1/armcomplexes" :op :list :entity "ArmComplex"}
   {:method "GET" :path "/v1/armcomplexes/:id" :op :get :entity "ArmComplex"}
   {:method "PATCH" :path "/v1/armcomplexes/:id" :op :update :entity "ArmComplex"}
   {:method "DELETE" :path "/v1/armcomplexes/:id" :op :delete :entity "ArmComplex"}
   {:method "POST" :path "/v1/flowtables" :op :create :entity "FlowTable"}
   {:method "GET" :path "/v1/flowtables" :op :list :entity "FlowTable"}
   {:method "GET" :path "/v1/flowtables/:id" :op :get :entity "FlowTable"}
   {:method "PATCH" :path "/v1/flowtables/:id" :op :update :entity "FlowTable"}
   {:method "DELETE" :path "/v1/flowtables/:id" :op :delete :entity "FlowTable"}
   {:method "POST" :path "/v1/offloads" :op :create :entity "Offload"}
   {:method "GET" :path "/v1/offloads" :op :list :entity "Offload"}
   {:method "GET" :path "/v1/offloads/:id" :op :get :entity "Offload"}
   {:method "PATCH" :path "/v1/offloads/:id" :op :update :entity "Offload"}
   {:method "DELETE" :path "/v1/offloads/:id" :op :delete :entity "Offload"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"dpus" {:create create-dpu :list list-dpus :get get-dpu :update update-dpu :delete delete-dpu}
   "packetpipelines" {:create create-packet-pipeline :list list-packet-pipelines :get get-packet-pipeline :update update-packet-pipeline :delete delete-packet-pipeline}
   "rdmaengines" {:create create-rdma-engine :list list-rdma-engines :get get-rdma-engine :update update-rdma-engine :delete delete-rdma-engine}
   "armcomplexes" {:create create-arm-complex :list list-arm-complexes :get get-arm-complex :update update-arm-complex :delete delete-arm-complex}
   "flowtables" {:create create-flow-table :list list-flow-tables :get get-flow-table :update update-flow-table :delete delete-flow-table}
   "offloads" {:create create-offload :list list-offloads :get get-offload :update update-offload :delete delete-offload}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "dpu_smartnic-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
